on: 
  push:
    branches:
      - main
      - dev
jobs: 
  build-container:
    name: build-container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: conf/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/snomics_to_seurat:latest
      


            